### ISSUE TITLE
Meetup data as JSON/YAML

### ISSUE THREAD

**Issue by zerok** [writethedocs/www#227]
Would it make sense to make the meetup data machine-parsable using something YAML(preferred) or JSON similar to what we have right now with the talks? This might help with re-using meetup information for the video archive and other future endeavours ;)

**Comment by plaindocs** [comment]
Yes, absolutely. I'll track down the list of meetup talks we have. 

Thoughts on 

* a file per meetup containing videos in exactly the same format as speaker files
* a single file of meetup videos with the meetup info inside the json

**Comment by zerok** [comment]
Oh, I'm more talking about the meetups themselves, basically what we have right now on http://www.writethedocs.org/meetups/

Should we there perhaps generate a file per meetup containing something like this?

```yaml
country: USA
state: New York
city: New York City
notes: |
  Organised by [@WriteTheDocsNYC](https://twitter.com/WriteTheDocsNYC)
sessions:
  - title: Some session
    speakers: ...
```
